---
# defaults file for curator

elasticsearch_curator_config_directory: /opt/carnival/config/

elasticsearch_curator_version: 5.7.6

elasticsearch_curator_cron_jobs:
  - name: "Run elasticsearch curator actions."
    job: "/bin/curator --config /opt/carnival/config/curator_config.yml /opt/carnival/config/curator_action.yml"
    minute: 05
    hour: 0

elasticsearch_curator_yaml: |
    ---
    client:
        hosts:
            - 127.0.0.1
        port: 9200
        url_prefix:
        use_ssl: False
        certificate:
        client_cert:
        client_key:
        ssl_no_validate: False
        http_auth: elastic:changeme
        timeout: 30
        master_only: False
        
        logging:
        loglevel: INFO
        logfile:
        logformat: default